### PR TITLE
Add ability to generate debfiles

### PR DESCRIPTION
**Pull request by ConnorRigby**

### CODE REVIEW

**Review by jjcarstens — APPROVED** [review]
LGTM

**Comment by fhunleth** [comment]
I need to think more about this since it seems like if we're packaging a deb file, there's no advantage to having a self extractor. I'm for holding off until we have fresh brains again if that's alright.

**Comment by mateuszkwiatkowski** [comment]
> I need to think more about this since it seems like if we're packaging a deb file, there's no advantage to having a self extractor.

What about support for non-deb distributions and other operating systems without self-extractor?

**Comment by fhunleth** [comment]
@mateuszkwiatkowski Thanks for the question. We're going to have to scope out what we can address with this project. The original intention was only the self-executable case since there already are Elixir packager libraries for RPMs, etc. Perhaps those need some improvements, but my opinion is that Bakeware has solid support for this one use case and reevaluate after that if there's a need for supporting others.

**Comment by fhunleth** [comment]
I'm going to close this. The focus is currently to fix up the one self-extracting release runner use case. Other projects can improve upon packaging for debs, rpms, etc.

**Pull request closed without merging**
